### ISSUE TITLE
Release to PyPi

### ISSUE THREAD

**Issue by hbruch** [tommyjcarpenter/osmtogeojson#4]
@tommyjcarpenter thx for creating this lib, which comes handy as geojson support of [mvexel/overpass-api-python-wrapper](https://github.com/mvexel/overpass-api-python-wrapper) is incomplete.

However, to provide a PR, it would be helpful, if osmtogeojson would be released to PyPi.

**Comment by tommyjcarpenter** [comment]
@hbruch hey thanks for your interest!
I never released this to PyPi because I had no idea how complete it was.

This project started because we had a bunch of python projects that needed to convert overpass results to geojson. So we had ugly system calls all over the place calling out to the famous NPM package, which is great because that package works and seems complete, but is nasty from an efficiency perspective (Syscall for every conversion).

As I got into this project however, I realized there were all these crazy rules around "winding order" etc, that I didn't have time at the time to sit down and fix. Maybe if there was more interest I would, but I kinda abondoned this when I got down into those weeds out of lack of interest (it seems the NPM package is king),

**Comment by hbruch** [comment]
Same here, I'm writing a small python tool to generate geojson layers using overpass to display them in @joto's [osmoscope-ui](https://github.com/osmoscope/osmoscope-ui/). I strive for a python-only solution, too.

**Comment by tommyjcarpenter** [comment]
ok it's there: https://pypi.org/project/osmtogeojson/

I want to note that this was still in infancy and by no means would have been considered release-worthy =). But, if you find it useful, I'm happy to help.

**Comment by hbruch** [comment]
Thanks a lot. As always, every new use case will rise new feature requests and uncover some issues, but having it published is already a good start :-)
